Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "public_network", auto_config: false

  # manual ip
  config.vm.provision "shell",
                      run: "always",
                      inline: "ifconfig eth1 192.168.1.74 netmask 255.255.252.0"

  # # router
  config.vm.provision "shell",
                      run: "always",
                      inline: "route add default gw 192.168.0.253"
end
